/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.alkal.examples.key_rotation.secured_service;

import static spark.Spark.get;

public class App {


    public static void main(String[] args) {

        AuthService authService=new AuthService();
        authService.init();


        get("/securedHelloWorld", "application/json", (request, response) -> {
            String token = request.headers("token");
            if (authService.isTokenAllows("greet",token))
                return "Hello World";
            else
                return "Invalid token :(";

        });


    }


}
