/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.alkal.kalium.demos.rolling_keys.models;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
